#!/usr/bin/env python3
import os
import textwrap

import yaml
import sys
import textwrap

from jinja2 import Template

from dialog import Dialog

from helpers import load_template_sets_yamls


def acknowledge_errors_or_exit(dlg, error_list):
    wrapped_messages = []
    summary_text = ""
    for error_msg in error_list:
        wrapped_lines = textwrap.wrap(error_msg, 50, subsequent_indent=2)
        wrapped_message = "\n".join(wrapped_lines)
        wrapped_messages.append(wrapped_message)

    summary_text += wrapped_message + "\n"
    dlg.scrollbox(summary_text, height=20, width=64,
                  title="Errors from Template sets Load operation.",
                  backtitle="Chromers")


def select_template_set_from_menu(dlg, template_sets_info_list):
    # Unpack info tuples
    menu_list = []
    for template_set in template_sets_info_list:
        base_dir, config_obj = template_set
        menu_list.append(
            (config_obj['short_name'], config_obj['short_description'], False)
        )

    selected_sets = dlg.checklist(
        "Select Template set to begin with",
        choices=menu_list,
        title="Select Template Set",
        width=70,
        list_height=5,
        height=12,
        backtitle="Chromers",
    )
    return selected_sets


def main():
    d = Dialog(dialog="dialog")

    TEMPLATE_SETS_DIR = "../template_sets"
    main_args = []  # Args that will go into generated scripts' main()
                    # signature

    templates_dir = os.path.abspath(os.path.join(os.getcwd(), TEMPLATE_SETS_DIR))

    template_sets_info, template_errors_list = load_template_sets_yamls(templates_dir)

    if len(template_errors_list) > 0:
        acknowledge_errors_or_exit(d, template_errors_list)

    selected_template = select_template_set_from_menu(d, template_sets_info)

    #
    # # Get list of client spec 'short_name' values using Dialog menu
    # status, selected_clients = client_select_menu(d, client_choices_menu)
    # if status != 'ok':
    #     print("\nAborted on client selection!\n")
    #     sys.exit(1)

    # wrapped_main_args = wrap_main_args(main_args)

    # output = script_template.render(
    #     switch_flags=switch_flags,
    #     main_args=main_args,
    #     wrapped_main_args=wrapped_main_args,
    #     instance_templates=instance_templates,
    #     prefix=entered_prefix,
    #     client_args_list=client_args_list,
    #     imports_list=imports_list,
    #     app_title=script_name,
    # )
    #
    # with open(f"output/{script_name}", "w") as output_script:
    #     output_script.write(output)


if __name__ == "__main__":
    main()
